version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pbkdf2
    versions:
    - 0.6.0
    - 0.7.1
    - 0.7.2
    - 0.7.3
    - 0.7.4
  - dependency-name: bootloader
    versions:
    - 0.9.14
  - dependency-name: smoltcp
    versions:
    - 0.7.0
  - dependency-name: volatile
    versions:
    - 0.4.3
  - dependency-name: spin
    versions:
    - 0.7.1
  - dependency-name: time
    versions:
    - 0.2.25
  - dependency-name: array-macro
    versions:
    - 2.0.0
  - dependency-name: linked_list_allocator
    versions:
    - 0.8.11
  - dependency-name: rand_core
    versions:
    - 0.6.1
  - dependency-name: x86_64
    versions:
    - 0.13.1
  - dependency-name: sha2
    versions:
    - 0.9.2
