[package]
name = "moros"
description = "MOROS: Obscure Rust Operating System"
version = "0.6.0"
authors = ["Vincent Ollivier <v@vinc.cc>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/vinc/moros"
readme = "README.md"

[features]
default = ["video", "rtl8139"]
video = []
serial = []
rtl8139 = []
pcnet = []

[dependencies]
acpi = "4.0.0"
aml = "0.16.0"
array-macro = "2.1.0"
base64 = { version = "0.13.0", default-features = false }
bit_field = "0.10.0"
bootloader = { version = "0.9.19", features = ["map_physical_memory"] }
float-cmp = "0.9.0"
hmac = { version = "0.11.0", default-features = false }
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
libm = "0.2.1"
linked_list_allocator = "0.9.0"
littlewing = { version = "0.7.0", default-features = false }
object = { version = "0.26.2", default-features = false, features = ["read"] }
pbkdf2 = { version = "0.9.0", default-features = false }
pc-keyboard = "0.5.1"
pic8259 = "0.10.2"
rand = { version = "0.8.4", default-features = false }
rand_chacha = { version = "0.3.0", default-features = false }
rand_core = { version = "0.6.3", default-features = false }
raw-cpuid = "10.2.0"
sha2 = { version = "0.9.8", default-features = false, features = ["force-soft"] }
smoltcp = { version = "0.7.5", default-features = false, features = ["alloc", "ethernet", "socket-tcp", "socket-udp", "proto-ipv4", "proto-dhcpv4"] }
spin = "0.9.2"
time = { version = "0.3.3", default-features = false }
uart_16550 = "0.2.15"
vte = "0.10.1"
x86_64 = "0.14.6"

[package.metadata.bootimage]
test-success-exit-code = 33 # (0x10 << 1) | 1
